
# test_download_speed.py
# 
# prof. lehman
#
# january 2026
#
# automated tests for download.py
# code generated by ChatGpt 5.2 and slightly modified
#
# test_download_speed.py and download_speed.py must be in same location
#

import subprocess
import sys
import math

def run_test(input_data, expected_speed):
    """
    Runs download_speed.py with simulated input and checks output.
    """
    result = subprocess.run(
        [sys.executable, "download_speed.py"],
        input=input_data,
        text=True,
        capture_output=True
    )

    output = result.stdout.strip()

    try:
        # Extract the numeric value from the output
        reported_speed = float(output.split("=")[1].split()[0])
    except:
        print("Output format incorrect:", output)
        return

    if math.isclose(reported_speed, expected_speed, rel_tol=1e-2):
        print(f"PASS | Input: {input_data.replace(chr(10), ', ')} → {reported_speed}")
    else:
        print(f"FAIL | Expected {expected_speed}, got {reported_speed}")

# -------------------------
# Test Cases
# -------------------------

# note: input is delimited by \n

# Test 1
# 3.5 MB file, 2 minute (30 sec)
# total_mb = 3.5 * 1024 = 3,584 mb
# total_speed = 2 * 60 + 30 = 150 seconds
# speed = 3,584 / 150 = 23.89 MB per second
run_test("3.5\n2\n30\n", 23.89)


# Test 2
# 4.25 MB file, 3 minutes (45 sec)
# total_mb = 4.25 * 1024 = 4,352 mb
# total_seconds = 3 * 60 + 45 = 225 seconds
# speed = 4,352 / 225 = 19.34 MB per second
run_test("4.25\n3\n45\n", 19.34)




